blueprint:
  name: IKEA Bilresa Dual Button Light Dimmer Remote
  description: |
    Use IKEA Bilresa Dual Button as a light remote.
    
    Single presses turn the light(s) on/off.
    Double presses and Button holds can be configured to either adjust brightness or trigger custom actions.

    Double Press Brightness Control: Adjusts brightness by a set percentage with each double press.
    Press and Hold Brightness Control: Smoothly ramps brightness up or down while the button is held.
    
    *Fields marked with * require the light entity selected to support transitions to function as expected.
  source_url: https://github.com/Kaito-Mez/HA-Blueprints/blob/main/IKEA/IKEA_Bilresa_Dual_Button.yaml
  domain: automation
  input:
    remote_up:
      name: Bilresa Remote - Up button event entity
      selector:
        entity:
          domain: event
    remote_down:
      name: Bilresa Remote - Down button event entity
      selector:
        entity:
          domain: event
    switch_entity:
      name: Switch Entity to Control
      description: Shelly switch.
      selector:
        entity:
          domain: switch
    light_entity:
      name: Light Entity to Control
      description: Create a Light Group Helper to control more than one light.
      selector:
        entity:
          domain: light
    double_click_mode:
      name: Double Click Behaviour
      description: >
        Choose the double click behaviour
      default: none
      selector:
        select:
          options:
            - label: None
              value: none
            - label: Brightness Stepper (Options Below)
              value: brightness
            - label: Custom Actions (Configuration Below Required)
              value: custom
    stepper_options:
      name: Brightness Stepper Options
      collapsed: true
      input:
        brightness_step_size:
          name: Brightness Step Percent
          description: How much to change the brightness per increment (Default 14%)
          default: 14
          selector:
            number:
              min: 1
              max: 50
              step: 1
              unit_of_measurement: "%"
        brightness_step_transition:
          name: Brightness Transition Time*
          description: Smoothness of each step (Default 0.4s)
          default: 0.4
          selector:
            number:
              min: 0
              max: 1.5
              step: 0.1
              unit_of_measurement: s
    custom_double_click_actions:
      name: Configure Double Click Custom Actions
      collapsed: true
      input:
        double_click_up_action:
          name: Double Click Up Action
          default: []
          selector:
            action: {}
        double_click_down_action:
          name: Double Click Down Action
          default: []
          selector:
            action: {}
    press_and_hold_mode:
      name: Press and Hold Behaviour
      description: >
        Choose the press and hold behaviour
      default: none
      selector:
        select:
          options:
            - label: None
              value: none
            - label: Brightness Dimmer* (Options Below)
              value: brightness
            - label: Custom Actions (Configuration Below Required)
              value: custom
    dimmer_options:
      name: Brightness Dimmer Options
      collapsed: true
      input:
        brightness_dimming_speed:
          name: Dimming Speed*
          description: How fast the brightness should change (Default 100%)
          default: 100
          selector:
            number:
              min: 50
              max: 200
              step: 1
              unit_of_measurement: "%"
    advanced_dimming_options:
      name: Advanced Dimmer Options
      description: |
        Leave these as default unless you notice the brightness rubberbanding up and down when you release the button.
        This is caused by delays in the light reporting its brightness back to Home Assistant.
        Below are controls to help compensate for this limitation.
      collapsed: true
      input:
        latency_compensation_offset:
          name: Brightness Extrapolation Offset
          description: |
            Fine tune the brightness extrapolation. (Default 0.06s) 
            
            Increase slightly if you see it rubberband back when releasing the button.
            Lower slightly if you see the light overshoot when releasing the button.
          default: 0.06
          selector:
            number:
              min: -0.2
              max: 0.2
              step: 0.005
              unit_of_measurement: s
        release_transition:
          name: Release Transition Interval*
          description: |
            Smoothness of the transition to the extrapolated brightness when you release the button. (Default 0.2s)

            Increase for a smoother transition at the cost of perceived latency.
            Decrease for a more abrupt transition that may feel snappier.
            Set to 0 for no transition.
          default: 0.2
          selector:
            number:
              min: 0
              max: 1.5
              step: 0.05
              unit_of_measurement: s
    custom_press_and_hold_actions:
      name: Configure Press and Hold Custom Actions
      collapsed: true
      input:
        hold_up_action:
          name: Hold Up Action
          default: []
          selector:
            action: {}
        hold_down_action:
          name: Hold Down Action
          default: []
          selector:
            action: {}
variables:
  switch_entity: !input switch_entity
  light_entity: !input light_entity

  double_click_mode: !input double_click_mode
  brightness_step_size: !input brightness_step_size
  brightness_step_transition: !input brightness_step_transition

  press_and_hold_mode: !input press_and_hold_mode

  brightness_dimming_speed: !input brightness_dimming_speed

  release_transition: !input release_transition
  latency_compensation_offset: !input latency_compensation_offset

  base_ramp_time: 3 # The time it takes to go from 0 to 255 brightness at 100% dimming speed
  speed_scalar: "{{ brightness_dimming_speed / 100 }}"
  scaled_ramp_time: "{{ base_ramp_time / speed_scalar }}"

triggers:  
  - trigger: state
    entity_id: !input remote_up
    id: press_up
    not_from: unavailable
    not_to: unavailable
  - trigger: state
    entity_id: !input remote_down
    id: press_down
    not_from: unavailable
    not_to: unavailable
  - trigger: state
    entity_id: !input remote_up
    attribute: event_type
    to: long_press
    id: hold_up
    not_from: unavailable
  - trigger: state
    entity_id: !input remote_down
    attribute: event_type
    to: long_press
    id: hold_down
    not_from: unavailable

mode: single # If the automation is triggered again while already running, the new trigger is ignored.
max_exceeded: silent # Dont Log warning when the new trigger is dropped.

actions:
  - choose:
      # Single Press UP Turns Light On
      - conditions:
          - condition: trigger
            id: press_up
          - condition: state
            entity_id: !input remote_up
            state:
              - multi_press_1
            attribute: event_type
        sequence:
          - action: switch.turn_on
            target:
              entity_id: !input switch_entity
              
      # Single Press DOWN Turns Light Off
      - conditions:
          - condition: trigger
            id: press_down
          - condition: state
            entity_id: !input remote_down
            state:
              - multi_press_1
            attribute: event_type
        sequence:
          - action: switch.turn_off
            target:
              entity_id: !input switch_entity

      # Double Press UP
      - conditions:
          - condition: trigger
            id: press_up
          - condition: state
            entity_id: !input remote_up
            state:
              - multi_press_2
            attribute: event_type
        sequence:
          # Brightness Control
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ double_click_mode == 'brightness' }}"
                sequence:
                  - action: light.turn_on
                    target:
                      entity_id: !input light_entity
                    data:
                      brightness_step_pct: "{{ brightness_step_size }}"
                      transition: "{{ brightness_step_transition }}"

          # Custom Action
          - choose: 
              - conditions:
                  - condition: template
                    value_template: "{{ double_click_mode == 'custom' }}"
                sequence: !input double_click_up_action
      
      # Double Press DOWN
      - conditions:
          - condition: trigger
            id: press_down
          - condition: state
            entity_id: !input remote_down
            state:
              - multi_press_2
            attribute: event_type
        sequence:
          # Brightness Control
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ double_click_mode == 'brightness' }}"
                sequence:
                  - action: light.turn_on
                    target:
                      entity_id: !input light_entity
                    data:
                      brightness_step_pct: "{{ brightness_step_size * -1 }}"
                      transition: "{{ brightness_step_transition }}"
          
          # Custom Action
          - choose: 
              - conditions:
                  - condition: template
                    value_template: "{{ double_click_mode == 'custom' }}"
                sequence: !input double_click_down_action
      
      # Hold UP
      - conditions:
          - condition: trigger
            id: hold_up
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ press_and_hold_mode == 'brightness' }}"
                sequence:
                  - if:
                      - condition: state
                        entity_id: !input light_entity
                        state: "off"
                    then:
                      - action: light.turn_on
                        target:
                          entity_id: !input light_entity
                        data:
                          brightness_pct: 1
                  - variables:
                      hold_start_time: "{{ as_timestamp(now()) - latency_compensation_offset }}"
                      hold_start_brightness: "{{ state_attr(light_entity, 'brightness') or 0 }}"
                  - action: light.turn_on
                    target:
                      entity_id: !input light_entity
                    data:
                      brightness: 255
                      transition: "{{ (1 - (hold_start_brightness / 255)) * scaled_ramp_time }}"
                  - wait_for_trigger:
                      - trigger: state
                        entity_id: !input remote_up
                        attribute: event_type
                        to: long_press
                    timeout: 30
                  - action: light.turn_on
                    target:
                      entity_id: !input light_entity
                    data:
                      brightness: "{{ [hold_start_brightness + (255 / scaled_ramp_time * (as_timestamp(now()) - hold_start_time)), 255] | min }}"
                      transition: "{{ release_transition }}"
          # Custom Action
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ press_and_hold_mode == 'custom' }}"
                sequence: !input hold_up_action

      # Hold DOWN
      - conditions:
          - condition: trigger
            id: hold_down
        sequence:
          # Smooth Brightness Control
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ press_and_hold_mode == 'brightness' }}"
                sequence:
                  - variables:
                      hold_start_time: "{{ as_timestamp(now()) - latency_compensation_offset }}"
                      hold_start_brightness: "{{ state_attr(light_entity, 'brightness') or 0 }}"
                  - action: light.turn_on
                    target:
                      entity_id: !input light_entity
                    data:
                      brightness: 1 # We cant set brightness to 0 or it turns the light off. The release transition is able to turn it off anyway
                      transition: "{{ (hold_start_brightness / 255) * scaled_ramp_time }}"
                  - wait_for_trigger:
                      - trigger: state
                        entity_id: !input remote_down
                        attribute: event_type
                        to: long_press
                    timeout: 30
                  - action: light.turn_on
                    target:
                      entity_id: !input light_entity
                    data:
                      brightness: "{{ [hold_start_brightness - (255 / scaled_ramp_time * (as_timestamp(now()) - hold_start_time)), 0] | max }}"
                      transition: "{{ release_transition }}"
          # Custom Action
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ press_and_hold_mode == 'custom' }}"
                sequence: !input hold_down_action
